### ISSUE TITLE
SSL Certificate issue with FHIR API

### ISSUE THREAD

**Issue by sfamini** [GEHealthcare/apiserver.gehealthcare.com#25]
Hi, 
We are a Virence VAR and trying to setup the FHIR endpoint on one of our test servers. It looks like the SSL certificate that was installed as part of CPS is not valid, and so the API won't work. Where can we get a valid certificate, or how can we fix it?

Here's the error I get: 
AuthenticationException: The remote certificate is invalid according to the validation procedure.

Thanks
Safa

**Comment by SameerSingh1991** [comment]
SSL certificates are used for encrypting the transfer of data between a browser and a web server. When we obtain SSL certificate from a Certificate Authority it is bound to our domain name by the certifying authority. So when we add the SSL certificate to our web server and someone tries to access our website over HTTPS the browser will immediately perform an SSL handshake and will show secured icon on the address bar. SSL certificate also helps to identify the organization to which we are trying to interact.

The SSL certificates installed as part of CPS are not useful for setting up FHIR server. When you setup FHIR server on a server with an IP address you will mostly map it to a domain name to make it globally accessible. This domain name will be accessed over HTTPS for security reasons. In order to make it accessible over HTTPS you will have to purchase an SSL certificate along with your domain name , activate the SSL certificate, map it to your domain name and import it to your Jboss. This will make your FHIR server secure while accessing it from browser or nodejs. Usually SSL certificates are available for purchase along with domain names.

**Comment by sfamini** [comment]
@SameerSingh1991: Thanks for the input. Makes sense when I think about it.
