### ISSUE TITLE
Unable to get recent encounter from fhir/r4/Encounter endpoints

### ISSUE THREAD

**Issue by balamurugan-clustrex** [GEHealthcare/apiserver.gehealthcare.com#281]
Description:
I am experiencing issues when trying to retrieve recent encounters from the FHIR R4 Encounter endpoint. Here are the details of the problem:

Steps to Reproduce:
1. Try OAuth2.0 in Postman or Web UI

Expected behavior:
I expect to receive the most recent encounter for the specified patient.

Additional Information:
https://ap22sandbox.fhirapi.athenahealth.com/demoAPIServer/fhir/r4/Encounter?patient=1225794134051060&_sort=-date&_count=1. I try this for descending order but not working. It always gives first record only.

I appreciate any assistance or guidance in resolving this issue and obtaining the most recent encounter for the specified patient.

**Comment by athena-Interop** [comment]
Sorting resources in response Bundles is not supported by the athenaPractice or athenaFlow FHIR servers.  The metadata API returns a CapabilityStatement that does not contain _sort in any of the CapabilityStatement.rest.resource.searchParam elements. 

We are sorry for the confusion.
FHIR specification of [_sort search parameter](https://hl7.org/fhir/r4/search.html#sort)
states "The server returns the sort it performs as part of the returned search parameters (see [Server Conformance for search](https://hl7.org/fhir/r4/search.html#conformance).")

Since the _sort parameter value is ignored, the _sort parameter should be omitted from the Bundle.link.url elements.  This is a bug.

This issue is a future enhancement request to support a FHIR Encounter request that would return a response with the most recent encounter.

**Comment by AjeetYadav07** [comment]
Thanks @balamurugan-clustrex, we will address this issue in future release.
