### ISSUE TITLE
Fetching appointments, their patients and practitioners data.

### ISSUE THREAD

**Issue by UjjwalChoudhariBirdeye** [GEHealthcare/apiserver.gehealthcare.com#29]
1. Could you please let us know how to filter the encounter based on any date and status.

We tried with the below URL but did not got the result - 

https://apisandbox.gehealthcare.com:9443/demoAPIServer/fhir/Encounter?_format=json&_summary=true&date=eq2018-05-21&status=finished

2. In the call to get the auth code, is the parameter  "aud" mandatory?

3. Why it always ask for personnel / work account even if I change the scope parameters. We want to fetch all encounters data. On production environment also, If I give the scope as user/*.* so that I can fetch all the encounters , it still ask for a patient / work account login. 

4. Can there be multiple entries of encounter for same patient for any particular day? We tried the encounter api and got multiple entires of same patient in response. 

5. We may have a client who have multi locations clinics/ hospitals etc. How is this managed in GE? How can we get the encounters of any particular location of any business among his multiple locations?

6. To fetch all the encounters of a day and its patients and practitioners data, we require to use offline_access and user/*.* as the scope values. Kindly confirm whether we are doing it correct or not.

**Comment by SameerSingh1991** [comment]
1. Yes the URL which you are using appears correct . Following get request will give you Encounter based on the conditions. There is not data for Encounter on date 2018-05-21 that is why you are not getting any result. I changed the date to 2018-05-17 and was able to get an encounter.
https://apisandbox.gehealthcare.com:9443/demoAPIServer/fhir/Encounter?_format=json&_summary=true&date=eq2018-05-17&status=finished

2. Yes aud is mandatory.

3. We are working on this.

4. Yes . Please go through the example use cases of Encounter from the following link.
https://www.hl7.org/fhir/DSTU2/encounter.html#examples

5. We have a Location resource in FHIR to specify particular locations. Encounter has a location search parameter which you can use to get Encounters based on Location. Check the below link for all search parameters of Encounter resource.
https://www.hl7.org/fhir/DSTU2/encounter.html#search

6. Can you please elaborate/explain on "we require to use offline_access" ? Since you only want to fetch Encounter, Patient and Practitioner resource the scope should be "user/Encounter.read user/Patient.read user/Practitioner.read".

**Comment by UjjwalChoudhariBirdeye** [comment]
3. Is this process going to change?

**Comment by SameerSingh1991** [comment]
Yes it will be simplified , instead of going to the personnel / work account selection page you will be redirected to the login page based on the scope parameters that you send.

**Comment by SameerSingh1991** [comment]
Closing this issue. Please reopen if you still encounter this issue.
