### ISSUE TITLE
Referral Source

### ISSUE THREAD

**Issue by schlueterryan** [GEHealthcare/apiserver.gehealthcare.com#293]
Is there a way to set "referral source" through the API? I could not find anything related to that field in the docuemtation

![image](https://github.com/athenahealth/apiserver-athenaFlex/assets/5241146/51a901df-170b-427d-b0c4-432a9e7aef5b)

**Comment by deepaktiwari29** [comment]
Hello @schlueterryan, 

Currently our FHIR R4 Appointment resource doesn't support referral source. In order to support referral source, we need to create an extension to the FHIR R4 Appointment resource which we are not planning for in near future.
You can refer this documentation for FHIR R4 Appointment resource related info: https://mydata.athenahealth.com/fhirapidoc/r4
