### ISSUE TITLE
Making FHIR calls to a local instance of CPS

### ISSUE THREAD

**Issue by joncodesalot** [GEHealthcare/apiserver.gehealthcare.com#30]
Has anyone found the correct client_id or generated a client_id for making FHIR calls to a local instance of CPS?

I can use the public sandbox and grab data. However, when I try to make FHIR calls directed to my local CPS instance it always fails. I have tried mutiple client_ids listed throughout the config files/azure, but each time I try to call the authorize or token endpoints it returns messages saying my client_id is always invalid. 

A small side note: I know that FHIR is running as I am able to make FHIR calls to the fhir-unsecured endpoint for DSTU3. The DSTU2 for fhir-unsecured unfortunately returns an error.

Thanks!

**Comment by SameerSingh1991** [comment]
By local CPS server you mean to say local CPS FHIR server. If yes , we have a sample code to generate auth code and token which you can run locally. Following is the link to the code .

https://github.com/GEHealthcare/apiserver.gehealthcare.com/tree/master/token-generation-sample-code

You are getting client ID is invalid error because most probably you are using client IDs which have been generated for other applications and not your application.
Let us say that you have an application running on port 3000 locally on https (i.e https://localhost:3000/) and you want to generate a token for that application from the local CPS FHIR server. First you need to register your application on Centricity Developer Portal (https://mydata.gehealthcare.com) using your client URL (https://localhost:3000/) and a redirect URL like https://localhost:3000/redirect.html. Once you have successfully registered you will get a client ID and client secret which you can then use for code and token generation as per the steps mentioned in the sample code mentioned above.

**Comment by joncodesalot** [comment]
Thanks @SameerSingh1991 this cleared up my question!
