### ISSUE TITLE
Retrieving slots for sandbox practitioner

### ISSUE THREAD

**Issue by lindsay-davis-zocdoc** [GEHealthcare/apiserver.gehealthcare.com#317]
How do I retrieve a list of free slots for Practitioner/1225652472001060 in the Athena Practice v22 sandbox?

I am able to retrieve a list of schedules for this practitioner via this endpoint: 
{{base_url}}Schedule?active=true&actor=1225652472001060

I can view slot types via this endpoint:
{{base_url}}/Appointment/$lookup-type?practitioner=1225652472001060

From the Schedule endpoint, it appears that Schedule ID 71 should extend to 11/30/2024. I am trying to use that schedule ID to look up slots with the following format:
{{base_url}}/Slot?_id=1225652472001060&schedule=71&status=free&start=2024-10-22T00:00

This returns a 500 Internal Server Error with the below message:
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "error",
            "diagnostics": "BRP516E33"
        }
    ]
}

I have also tried to retrieve slots over the next 30 days from today with the following e[ndpoint format as outlined in the FHIR R4 documentation](https://docs.mydata.athenahealth.com/fhir-r4/StructureDefinition-athena-slot-profile.html):
{{base_url}}/Slot?_id=1225652472001060&schedule=71&status=free&start-fromnow=ge30||d
This returns a 400 Bad Request.

Can you please advise how to retrieve slots so I can book a test appointment with this provider?

**Comment by lindsay-davis-zocdoc** [comment]
I was able to figure this out and retrieve slots, however, I would still like to use the parameter start-fromnow = ge30||d as outlined in the documentation. I'm still getting a 400 bad request when I add this. Can you let me know how to format this parameter to get it to work?

**Comment by deepaktiwari29** [comment]
Hey @lindsay-davis-zocdoc ,
Thank you for reaching out to us. Your initial request appears to be failing due to an incorrect _id value. Try creating a request with a proper id value; it should work.
If you do not have a valid id value, you can still send the same request but exclude the _id query parameter, which should return all valid slots for your query.
Regarding your second query about start-fromnow, please try URL encoding for the value, which will get the intended result.
Here's an example:
{{base_url}}/Slot?schedule=71&status=free&start-fromnow=ge30%7C%7Cd

**Comment by lindsay-davis-zocdoc** [comment]
Thank you! This is working as intended.

**Comment by deepaktiwari29** [comment]
Thank you for the confirmation @lindsay-davis-zocdoc 
Since the issue has been resolved, marking it as closed.
